In [2]:
from tqdm import tqdm
import time
import json
from enum import Enum
from gurobipy import Model, GRB, quicksum, max_
import numpy as np
import pandas as pd
from random import randint
import plotly.graph_objs as go


In [3]:
class DATASET(Enum):
    TOY = "toy"
    MEDIUM = "medium"
    LARGE = "large"
    GEN_1 = "generated_1"
    GEN_2 = "generated_2"
    GEN_3 = "generated_3"

# Fonctions pour préparer le modèle


In [4]:
def load_data(name):
    """name must be an instance of DATASET like DATASET.TOY for example"""
    if not isinstance(name, DATASET):
        raise TypeError("direction must be an instance of DATASET Enum")
    with open(f"../data/{name.value}_instance.json", "r") as f:
        data = json.load(f)
    return data


def get_dims(data):
    return (
        len(data["staff"]),
        data["horizon"],
        len(data["qualifications"]),
        len(data["jobs"]),
    )

def get_qualification_index(list_qualifications, qualification): # qualification is "A", "B", "C" ...
    return list_qualifications.index(qualification)

In [5]:
def init_model():
    m = Model("Project modelling")
    return m

In [6]:
def create_decision_variables(model, n_staff, horizon, n_qualifs, n_jobs):
    X = model.addVars(n_staff, horizon, n_qualifs, n_jobs, vtype=GRB.BINARY, name="assignements")
    J = model.addVars(n_jobs, vtype=GRB.BINARY, name="completion")
    E_D = model.addVars(n_jobs, lb=0, ub=horizon, vtype=GRB.INTEGER, name="end_dates")
    L = model.addVars(n_jobs, lb=0, ub=horizon + 1, vtype=GRB.INTEGER, name="n_days_late")
    # profit 
    profit = model.addVar(lb =0, vtype = GRB.INTEGER, name = "profit")
    # for max(days spent on project) variable
    S_D = model.addVars(n_jobs, lb=0, ub=horizon, vtype=GRB.INTEGER, name="start_dates")
    spans = model.addVars(n_jobs, lb=0, ub=horizon, vtype=GRB.INTEGER, name="spans")
    max_days = model.addVar(lb=0, ub=horizon, vtype=GRB.INTEGER, name="max_jobs")
    # for max(projects affected) variable 
    n_jobs_per_person = model.addVars(n_staff, lb=0, ub=n_jobs, vtype=GRB.INTEGER, name="n_jobs_per_person")
    jobs_worked_on_by_person = model.addVars(n_staff, n_jobs, vtype=GRB.BINARY, name="jobs_worked_on_by_person")
    n_worked_days_per_job_and_person = model.addVars(n_staff, n_jobs,lb=0, ub=horizon, vtype=GRB.INTEGER, name="n_worked_days_per_job_and_person")
    max_jobs = model.addVar(lb=0, ub=n_jobs, vtype=GRB.INTEGER, name="max_jobs")
    return model, X, J, S_D, E_D, L, n_jobs_per_person, jobs_worked_on_by_person, n_worked_days_per_job_and_person, max_jobs, max_days, spans, profit


In [7]:
def add_constraints_start_dates(model, X, S_D, n_staff, horizon, n_qualifs, n_jobs):
    # model.addConstrs(
    #     (X[i, j, k, l] == 1) >> (X[i, j, k, l] * j >= S_D[l]) 
    #     for i in range(n_staff)
    #     for j in range(horizon)
    #     for k in range(n_qualifs)
    #     for l in range(n_jobs)
    # )
    model.addConstrs(
        S_D[l] <= X[i, j, k, l] * j + (1 - X[i, j, k, l]) * horizon
        for i in range(n_staff)
        for j in range(horizon) 
        for k in range(n_qualifs)
        for l in range(n_jobs)
    )

In [8]:
def add_constraints_end_dates(model, X, E_D, n_staff, horizon, n_qualifs, n_jobs):
    model.addConstrs(
        X[i, j, k, l] * j <= E_D[l] 
        for i in range(n_staff)
        for j in range(horizon)
        for k in range(n_qualifs)
        for l in range(n_jobs)
    )

In [9]:
def add_constraints_lateness(model, E_D, L, jobs, n_staff, horizon, n_qualifs, n_jobs):
    model.addConstrs(
        E_D[l] + 1 - jobs[l]["due_date"] <= L[l] for l in range(n_jobs)
    )

In [10]:
def add_constraints_worked_days_below_required_days(model, X, jobs, qualifications, n_staff, horizon, n_jobs):
    model.addConstrs(quicksum(X[i,j,get_qualification_index(qualifications, k),l] for i in range(n_staff) for j in range(horizon)) <= jobs[l]["working_days_per_qualification"][k] 
                     for l in range(n_jobs) 
                     for k in jobs[l]["working_days_per_qualification"].keys())
    

In [11]:
def add_constraints_worked_days_above_required_days(model, X, J, jobs, qualifications, n_staff, horizon, n_jobs):
    model.addConstrs(quicksum(X[i,j,get_qualification_index(qualifications, k),l] for i in range(n_staff) for j in range(horizon)) >= J[l]* jobs[l]["working_days_per_qualification"][k] 
                     for l in range(n_jobs) 
                     for k in jobs[l]["working_days_per_qualification"].keys())

    # for l in range(n_jobs): 
    #     for quali,njk in data["jobs"][l]["working_days_per_qualification"].items():
    #         model.addConstr(J[l]*njk <= quicksum([X[i,j,get_qualification_index(qualifications, quali),l] for i in range(n_staff) for j in range(horizon)]))

In [12]:
def add_constraints_employees_working_only_one_day(model, X, J, data, n_staff, n_jobs, horizon, n_qualifs):
    model.addConstrs(quicksum(X[i,j,k,l] for l in range(n_jobs) for k in range (n_qualifs)) <= 1 
                     for i in range(n_staff) 
                     for j in range(horizon))

In [13]:
def in_qualification(data, i, k):
    return data["qualifications"][k] in data["staff"][i]["qualifications"]


def add_qualification_constraints(model, n_staff, horizon, n_qualifs, n_jobs, X, data):
    model.addConstrs(
        X[i, j, k, l] == 0
        for i in range(n_staff)
        for j in range(horizon)
        for k in range(n_qualifs)
        for l in range(n_jobs)
        if not in_qualification(data, i, k)
    )


def in_vacation(i, j, data):
    data = {l: data["staff"][l] for l in range(len(data["staff"]))}
    data = data[i]["vacations"]
    return j in data


def add_vacation_constraints(model, n_staff, horizon, n_qualifs, n_jobs, X, data):
    model.addConstrs(
        X[i, j, k, l] == 0
        for i in range(n_staff)
        for j in range(horizon)
        for k in range(n_qualifs)
        for l in range(n_jobs)
        if in_vacation(i, j, data)
    )

In [14]:
def add_constraint_profit(model, J, L, profit, jobs):
    model.addConstr(profit == quicksum( (J[index_job] * job["gain"] - job["daily_penalty"] * L[index_job]) for index_job, job in enumerate(jobs)))

In [15]:
def add_constraints_n_worked_days_per_jobs_person(model, X, n_worked_days_per_job_and_person, n_staff, n_jobs, horizon, n_qualifs):
    model.addConstrs( n_worked_days_per_job_and_person[i, l] == quicksum( X[i,j,k,l] for j in range(horizon) for k in range(n_qualifs)) 
        for i in range(n_staff) 
        for l in range(n_jobs)
    )

def add_constraints_jobs_worked_on_by_person(model, jobs_worked_on_by_person, n_worked_days_per_job_and_person, n_staff, n_jobs):
    model.addConstrs((jobs_worked_on_by_person[i, l] == 0) >> (n_worked_days_per_job_and_person[i,l] == 0) 
        for i in range(n_staff) 
        for l in range(n_jobs)
    ) 
    # model.addConstrs((jobs_worked_on_by_person[i, l] <= n_worked_days_per_job_and_person[i,l]) 
    #     for i in range(n_staff) 
    #     for l in range(n_jobs)
    # ) 
    model.addConstrs((jobs_worked_on_by_person[i, l] == 1) >> (n_worked_days_per_job_and_person[i,l] >= 1) 
        for i in range(n_staff) 
        for l in range(n_jobs)
    )
    # model.addConstrs((n_worked_days_per_job_and_person[i, l] <= jobs_worked_on_by_person[i,l]*n_jobs) 
    #     for i in range(n_staff) 
    #     for l in range(n_jobs)
    # ) 

def add_constraints_n_jobs_per_person(model, n_jobs_per_person, jobs_worked_on_by_person, n_staff, n_jobs):
    model.addConstrs(n_jobs_per_person[i] == quicksum( jobs_worked_on_by_person[i, l] for l in range(n_jobs) ) for i in range(n_staff))

def add_constraint_max_jobs(model, max_jobs, n_jobs_per_person, jobs_worked_on_by_person, n_staff):
    model.addConstr(max_jobs == max_([n_jobs_per_person[i] for i in range(n_staff)]))

In [16]:
def add_constraint_spans(model, spans, E_D, S_D, n_jobs):
    model.addConstrs((spans[l] == (E_D[l] - S_D[l])+1) for l in range(n_jobs))

def add_constraint_max_days(model, max_days, spans, n_jobs):
    for l in range(n_jobs):
        model.addConstr(max_days >= spans[l]) 
    # model.addConstr(max_days == max_([spans[l] for l in range(n_jobs)]))

In [17]:
def add_profit_as_first_objective(model, J, L, jobs):
    model.setObjective(
        quicksum( (J[index_job] * job["gain"] - job["daily_penalty"] * L[index_job]) for index_job, job in enumerate(jobs)),
        GRB.MAXIMIZE
    )
    return model

## add pouieme des autres

In [18]:
def add_minimax_jobs_as_second_objective(model, max_jobs):
    model.setObjective(
        max_jobs,
        GRB.MINIMIZE
    )
    return model

In [19]:
def add_minimax_days_spent_as_third_objective(model, max_days):
    model.setObjective(
        max_days,
        GRB.MINIMIZE
    )
    return model

In [20]:
def add_mono_objective(model, profit, max_days, max_jobs):
    model.setObjective(
        10 * profit - max_days - max_jobs,
        GRB.MAXIMIZE
    )
    return model, profit, max_days, max_jobs

# Surface

In [21]:
def prepare_model(data):
    n_staff, horizon, n_qualifs, n_jobs = get_dims(data)

    # Instanciation du modèle
    model = init_model()
    
    # Création des variables : binaires dans X et J, entières de 0 à horizon + 3
    model, X, J, S_D, E_D, L, n_jobs_per_person, jobs_worked_on_by_person, n_worked_days_per_job_and_person, max_jobs, max_days, spans, profit = create_decision_variables(model, n_staff, horizon, n_qualifs, n_jobs)
    
    # maj du modèle
    model.update()
    
    # Ajout des constraintes
    
    add_constraints_employees_working_only_one_day(model, X ,J,data,n_staff,n_jobs,horizon, n_qualifs)
    add_qualification_constraints(model, n_staff, horizon, n_qualifs, n_jobs, X, data)
    add_vacation_constraints(model, n_staff, horizon, n_qualifs, n_jobs, X, data)
    
    add_constraints_start_dates(model, X, S_D, n_staff, horizon, n_qualifs, n_jobs)
    add_constraints_end_dates(model, X, E_D, n_staff, horizon, n_qualifs, n_jobs)
    add_constraints_lateness(model, E_D, L, data["jobs"], n_staff, horizon, n_qualifs, n_jobs)
    
    add_constraints_worked_days_below_required_days(model, X, data["jobs"], data["qualifications"], n_staff, horizon, n_jobs)
    add_constraints_worked_days_above_required_days(model, X , J, data["jobs"], data["qualifications"], n_staff, horizon, n_jobs)
    
    add_constraints_n_worked_days_per_jobs_person(model, X, n_worked_days_per_job_and_person, n_staff, n_jobs, horizon, n_qualifs)
    add_constraints_jobs_worked_on_by_person(model, jobs_worked_on_by_person, n_worked_days_per_job_and_person, n_staff, n_jobs)
    add_constraints_n_jobs_per_person(model, n_jobs_per_person, jobs_worked_on_by_person, n_staff, n_jobs)
    add_constraint_spans(model, spans, E_D, S_D, n_jobs)
    
    add_constraint_profit(model, J, L, profit, data["jobs"])
    add_constraint_max_jobs(model, max_jobs, n_jobs_per_person, jobs_worked_on_by_person, n_staff)
    add_constraint_max_days(model, max_days, spans, n_jobs)
    
    
    # Fonctions Objectifs
    
    # model = add_minimax_jobs_as_second_objective(model, max_jobs)
    # model = add_minimax_days_spent_as_third_objective(model, max_days)
    # model = add_profit_as_first_objective(model, J, L, data["jobs"])
    
    model, profit, max_days, max_jobs = add_mono_objective(model, profit, max_days, max_jobs)
    
    # maj du modèle
    model.update()
    
    # Paramétrage (mode mute)
    model.params.outputflag = 0

    return model, profit, max_days, max_jobs

In [22]:
def main(dataset):
    data = load_data(dataset)
    n_staff, horizon, n_qualifs, n_jobs = get_dims(data)
    points = []
    for i in tqdm(range(horizon, -1, -1)):
        for j in range(n_jobs, -1, -1):
            print(j, " / ", n_jobs)
            model, profit, max_days, max_jobs = prepare_model(data)
            model.addConstr(max_jobs <= j)
            model.addConstr(max_days <= i)
            model.update()
            model.optimize()
            point = np.array([round(i), round(j), round(profit.X)])
            points.append(point)
    points = np.array(points)
    return points

    
    

In [23]:
dataset = DATASET.GEN_2
data = load_data(dataset)
n_staff, horizon, n_qualifs, n_jobs = get_dims(data)
points = main(dataset)
print(points)

  0%|          | 0/9 [00:00<?, ?it/s]

6  /  6
Set parameter Username
Academic license - for non-commercial use only - expires 2023-12-10
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 11%|█         | 1/9 [00:14<01:52, 14.08s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 22%|██▏       | 2/9 [00:32<01:55, 16.45s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 33%|███▎      | 3/9 [00:40<01:16, 12.70s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 44%|████▍     | 4/9 [00:51<01:00, 12.18s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 56%|█████▌    | 5/9 [01:04<00:49, 12.35s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 67%|██████▋   | 6/9 [01:37<00:57, 19.26s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 78%|███████▊  | 7/9 [02:05<00:44, 22.18s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6


 89%|████████▉ | 8/9 [02:12<00:17, 17.37s/it]

0  /  6
6  /  6
5  /  6
4  /  6
3  /  6
2  /  6
1  /  6
0  /  6


100%|██████████| 9/9 [02:12<00:00, 14.76s/it]

[[  8   6 128]
 [  8   5 128]
 [  8   4 128]
 [  8   3 128]
 [  8   2 128]
 [  8   1 109]
 [  8   0   0]
 [  7   6 128]
 [  7   5 128]
 [  7   4 128]
 [  7   3 128]
 [  7   2 128]
 [  7   1 109]
 [  7   0   0]
 [  6   6 128]
 [  6   5 128]
 [  6   4 128]
 [  6   3 128]
 [  6   2 128]
 [  6   1 102]
 [  6   0   0]
 [  5   6 128]
 [  5   5 128]
 [  5   4 128]
 [  5   3 128]
 [  5   2 128]
 [  5   1 102]
 [  5   0   0]
 [  4   6 128]
 [  4   5 128]
 [  4   4 128]
 [  4   3 128]
 [  4   2 126]
 [  4   1  91]
 [  4   0   0]
 [  3   6 128]
 [  3   5 128]
 [  3   4 128]
 [  3   3 128]
 [  3   2 117]
 [  3   1  76]
 [  3   0   0]
 [  2   6 128]
 [  2   5 128]
 [  2   4 128]
 [  2   3 117]
 [  2   2 102]
 [  2   1  65]
 [  2   0   0]
 [  1   6  50]
 [  1   5  50]
 [  1   4  50]
 [  1   3  50]
 [  1   2  50]
 [  1   1  50]
 [  1   0   0]
 [  0   6   0]
 [  0   5   0]
 [  0   4   0]
 [  0   3   0]
 [  0   2   0]
 [  0   1   0]
 [  0   0   0]]


# Visualisation

In [24]:
print(points[:,0])

[8 8 8 8 8 8 8 7 7 7 7 7 7 7 6 6 6 6 6 6 6 5 5 5 5 5 5 5 4 4 4 4 4 4 4 3 3
 3 3 3 3 3 2 2 2 2 2 2 2 1 1 1 1 1 1 1 0 0 0 0 0 0 0]


In [31]:
Z = np.array(points[:,2]).reshape(horizon+1,n_jobs+1)

X=np.linspace(horizon,0,horizon +1)
Y = np.linspace(n_jobs,0,n_jobs +1)
X, Y = np.meshgrid(X,Y)

print(X)
print(Y)
print(Z)


fig = go.Figure(data=[go.Surface(x=X, y=Y, z=Z.T)])
fig.update_layout(scene=dict(xaxis_title="Days", yaxis_title="Jobs", zaxis_title="Benefit"))
fig.show()

[[8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0.]]
[[6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[128 128 128 128 128 109   0]
 [128 128 128 128 128 109   0]
 [128 128 128 128 128 102   0]
 [128 128 128 128 128 102   0]
 [128 128 128 128 126  91   0]
 [128 128 128 128 117  76   0]
 [128 128 128 117 102  65   0]
 [ 50  50  50  50  50  50   0]
 [  0   0   0   0   0   0   0]]
